const C=window.CATALOGO, CFG=window.PANDA_CONFIG;let cart=JSON.parse(localStorage.getItem('panda_cart')||'[]'),shown=80;
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n),norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function productRow(p){return `<div class="product"><div class="product-name">${p.nombre}<span class="product-cat">${p.categoria}</span></div><span class="price">${money(p.precio)}</span><button class="add" data-id="${p.id}">Agregar</button></div>`}
function render(){let q=norm($('#search').value||''),f=$('#filter').value;let b=C.basicos.filter(x=>!q||norm(x.nombre).includes(q)),s=C.especiales.filter(x=>!q||norm(x.nombre).includes(q)),o=C.otros.filter(x=>!q||norm(x.nombre).includes(q));$('#basicos').hidden=f!=='todos'&&f!=='basicos';$('#especiales').hidden=f!=='todos'&&f!=='especiales';$('#otros').hidden=f!=='todos'&&f!=='otros';$('#basicTotal').textContent=`${b.length} productos disponibles`;$('#basicList').innerHTML=b.slice(0,shown).map(productRow).join('')||'<p style="padding:20px">Sin resultados.</p>';$('#loadMore').style.display=shown>=b.length?'none':'flex';$('#specialList').innerHTML=s.map(productRow).join('')||'<p style="padding:20px">Sin resultados.</p>';$('#otherList').innerHTML=o.map(productRow).join('')||'<p style="padding:20px">Sin resultados.</p>';document.querySelectorAll('.add').forEach(x=>x.onclick=()=>add(x.dataset.id));}
function all(){return [...C.basicos,...C.especiales,...C.otros]}function add(id){let p=all().find(x=>x.id===id),r=cart.find(x=>x.id===id);r?r.qty++:cart.push({...p,qty:1});save();toast('Producto agregado');}
function save(){localStorage.setItem('panda_cart',JSON.stringify(cart));$('#cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);renderCart()}
function renderCart(){if(!cart.length){$('#cartItems').innerHTML='<p>Tu carrito está vacío.</p>';$('#cartTotal').textContent=money(0);return}$('#cartItems').innerHTML=cart.map(x=>`<div class="cart-row"><div><b>${x.nombre}</b><small style="display:block">${money(x.precio)} c/u</small></div><div class="cart-actions"><button data-act="-" data-id="${x.id}">−</button><b>${x.qty}</b><button data-act="+" data-id="${x.id}">+</button></div></div>`).join('');$('#cartTotal').textContent=money(total());document.querySelectorAll('.cart-actions button').forEach(b=>b.onclick=()=>qty(b.dataset.id,b.dataset.act));}
function qty(id,a){let x=cart.find(y=>y.id===id);x.qty+=a==='+'?1:-1;if(x.qty<=0)cart=cart.filter(y=>y.id!==id);save()}function total(){return cart.reduce((a,x)=>a+x.precio*x.qty,0)}
function openCart(){ $('#cart').classList.add('open');$('#cart').setAttribute('aria-hidden','false');$('#shade').hidden=false}function closeCart(){$('#cart').classList.remove('open');$('#cart').setAttribute('aria-hidden','true');$('#shade').hidden=true}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
$('#search').oninput=()=>{shown=80;render()};$('#filter').onchange=render;$('#loadMore').onclick=()=>{shown+=100;render()};$('#cartOpen').onclick=openCart;$('#cartClose').onclick=closeCart;$('#shade').onclick=closeCart;
$('#checkoutOpen').onclick=()=>{if(!cart.length)return toast('Agrega productos al carrito');closeCart();$('#checkout').hidden=false};$('#checkoutClose').onclick=()=>$('#checkout').hidden=true;
$('#orderForm').zona.onchange=e=>{let min=e.target.value==='villa'?1000:e.target.value==='zmg'?1500:0;$('#minNotice').textContent=min?`Pedido mínimo para esta zona: ${money(min)}. Tu carrito suma ${money(total())}.`:'Recoger en farmacia no requiere pedido mínimo.'};
$('#orderForm').onsubmit=async e=>{e.preventDefault();let fd=Object.fromEntries(new FormData(e.target)),min=fd.zona==='villa'?1000:fd.zona==='zmg'?1500:0;if(total()<min){$('#status').textContent=`Faltan ${money(min-total())} para alcanzar el pedido mínimo.`;return}let payload={cliente:fd,productos:cart.map(({id,nombre,precio,qty})=>({id,nombre,precio,cantidad:qty,importe:precio*qty})),total:total(),origen:'Farmacia Panda'};let btn=e.target.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='Enviando...';$('#status').textContent='';try{let r=await fetch(CFG.API_URL+'/api/pedidos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error();let d=await r.json();$('#status').textContent=`Pedido enviado correctamente. Folio: ${d.folio}`;cart=[];save();e.target.reset();setTimeout(()=>{$('#checkout').hidden=true;toast('Pedido enviado correctamente')},1800)}catch(err){$('#status').innerHTML='No fue posible conectar con el servidor. Intenta nuevamente o usa el botón de WhatsApp.'}finally{btn.disabled=false;btn.textContent='Enviar pedido'}};render();save();